version: '3.9'
services:
  web_br:
    build: .
    container_name: django_app_br
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/app
    ports:
      - "8005:8000"
    env_file:
      - .env
    depends_on:
      - db_br
    networks:
      - django_network_br
  db_br:
    image: postgres:16
    container_name: postgres_db_br
    environment:
      POSTGRES_DB: django_db
      POSTGRES_USER: django_user
      POSTGRES_PASSWORD: django_password
    volumes:
      - postgres_data_br:/var/lib/postgresql/data
    ports:
      - "5437:5432"
    networks:
      - django_network_br

volumes:
  postgres_data_br:
networks:
  django_network_br: